spring.application.name=DeliveryDriverSystem

# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Server port
server.port=8081

# Required for JSP with embedded Tomcat
server.servlet.register-default-servlet=true

# Data file path
app.data.path=data/drivers.txt


spring.mvc.servlet.path=/